version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - mongo-data:/data/db

  api:
    build: ./apiPoke
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: toor
      MONGO_HOSTNAME: mongo
    volumes:
      - ./apiPoke:/app 

  webapp:
    build: ./mvc-pokemon
    ports:
      - "8080:8080"
    depends_on:
      - api
    volumes:
      - ./mvc-pokemon:/index

volumes:
  mongo-data:
    driver: local