version: "3.3"

services:
  # Nginx
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./mvc-pokemon:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  # Configuración de php .
  php-fpm:
    container_name: php
    build: .
    volumes:
      - ./mvc-pokemon:/var/www/html