version: '3'
services:
  api:
    build: ./apiPoke
    ports:
      - "3000:3000"
    volumes:
      - ./apiPoke:/usr/src/app 

  webapp:
    build: ./mvc-pokemon
    ports:
      - "8080:8080"
    depends_on:
      - api
    volumes:
      - ./mvc-pokemon:/usr/src/app 
      - ./mvc-pokemon/public:/usr/src/app/public

volumes:
  mongo-data:
    driver: local